---
- name: Add group "kafka"
  group: name={{ kafka_group }} system=yes

- name: Add user "kafka"
  user: name={{ kafka_user }} group={{ kafka_group }} shell=/sbin/nologin system=yes

- name: Download the tarball
  get_url: url="https://archive.apache.org/dist/kafka/1.0.0/kafka_2.11-1.0.0.tgz" dest=/opt/kafka_2.11-{{ kafka_version }}.tgz

- name: Extract the tarball
  unarchive: src=/opt/kafka_2.11-{{ kafka_version }}.tgz dest=/opt/ copy=no

- name: Symlink install directory
  file: src=/opt/kafka_2.11-{{ kafka_version }} path=/opt/kafka state=link owner=kafka group=kafka

- name: Set permissions to Kafka folder
  file: path=/opt/kafka/ owner=kafka group=kafka recurse=yes

- name: Create /kafka/data directory
  file: path=/kafka/data state=directory owner={{ kafka_user }} group={{ kafka_group }}
  when: data_disks_devices is not defined or not data_disks_devices or data_disks_devices|length <= 0

- name: Create Kafka log directory
  file: path={{ kafka_log_dir }} state=directory owner={{ kafka_user }} group={{ kafka_group }}

- name: Link the log directory
  file: src={{ kafka_log_dir }} path=/opt/kafka/logs state=link

- name: Create Kafka conf directory
  file: path={{ kafka_conf_dir }} state=directory owner=root group=root mode=755

- name: Install Kafka init script
  template: src=kafka-server.j2 dest=/etc/init.d/kafka-server mode=0755
  notify: Reload systemd

- name: Configure Kafka server
  template: src=server.properties.j2 dest="{{kafka_conf_dir}}/server.properties"

- name: Configure Kafka producer
  template: src=producer.properties.j2 dest="{{kafka_conf_dir}}/producer.properties"

- name: Configure Kafka consumer
  template: src=consumer.properties.j2 dest="{{kafka_conf_dir}}/consumer.properties"

- name: Upload log4j configs
  copy: src={{ item }} dest="{{ kafka_conf_dir }}/" owner=root group=root mode=644
  with_items:
    - log4j.properties
    - tools-log4j.properties

- name: Add Kafka binaries to PATH
  copy: src=kafka.sh dest=/etc/profile.d/ owner=root group=root mode=644
