---
- name: Add group "kafka"
  group: name={{ kafka_group }} system=yes

- name: Add user "kafka"
  user: name={{ kafka_user }} group={{ kafka_group }} shell=/sbin/nologin system=yes

- name: Download the tarball
  get_url: url="https://archive.apache.org/dist/kafka/1.0.0/kafka_2.11-1.0.0.tgz" dest=/opt/kafka_2.11-{{ kafka_version }}.tgz

- name: Extract the tarball
  unarchive: src=/opt/kafka_2.11-{{ kafka_version }}.tgz dest=/opt/ copy=no

- name: Symlink install directory
  file: src=/opt/kafka_2.11-{{ kafka_version }} path=/opt/kafka state=link owner=kafka group=kafka

- name: Set permissions to Kafka folder
  file: path=/opt/kafka/ owner=kafka group=kafka recurse=yes
